import { useForm } from '@inertiajs/react';
import InputError from '@/components/input-error';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import PublicLayout from '@/layouts/public-layout';

export default function OrderForm({ webServices, domains }) {
    const { data, setData, post, processing, errors } = useForm({ client_name: '', client_email: '', client_phone: '', order_type: 'website', web_service_id: '', domain_id: '', domain_name: '', notes: '', website_url: '' });
    function submit(e) { e.preventDefault(); post('/order'); }
    const needsWeb = ['website', 'both'].includes(data.order_type); const needsDomain = ['domain', 'both'].includes(data.order_type);
    return <PublicLayout title="Minta Penawaran"><form onSubmit={submit} className="mx-auto max-w-2xl space-y-4 px-4 py-12"><h1 className="text-3xl font-semibold">Minta Penawaran</h1><Input placeholder="Nama" value={data.client_name} onChange={(e) => setData('client_name', e.target.value)} required /><InputError message={errors.client_name} /><Input type="email" placeholder="Email" value={data.client_email} onChange={(e) => setData('client_email', e.target.value)} required /><InputError message={errors.client_email} /><Input placeholder="WhatsApp" value={data.client_phone} onChange={(e) => setData('client_phone', e.target.value)} required /><InputError message={errors.client_phone} /><select className="h-9 w-full rounded-lg border bg-background px-2 text-sm" value={data.order_type} onChange={(e) => setData('order_type', e.target.value)}><option value="website">Website</option><option value="domain">Domain</option><option value="both">Website + Domain</option></select>{needsWeb && <select className="h-9 w-full rounded-lg border bg-background px-2 text-sm" value={data.web_service_id} onChange={(e) => setData('web_service_id', e.target.value)}><option value="">Pilih paket</option>{webServices.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>}{needsDomain && <><Input placeholder="Nama domain, contoh: tokoku" value={data.domain_name} onChange={(e) => setData('domain_name', e.target.value)} /><select className="h-9 w-full rounded-lg border bg-background px-2 text-sm" value={data.domain_id} onChange={(e) => setData('domain_id', e.target.value)}><option value="">Pilih ekstensi</option>{domains.map((item) => <option key={item.id} value={item.id}>{item.extension}</option>)}</select></>}<textarea className="min-h-28 w-full rounded-lg border bg-transparent p-2 text-sm" placeholder="Catatan" value={data.notes} onChange={(e) => setData('notes', e.target.value)} /><input className="hidden" tabIndex="-1" autoComplete="off" value={data.website_url} onChange={(e) => setData('website_url', e.target.value)} /><Button disabled={processing}>Kirim</Button></form></PublicLayout>;
}
