name: CI/CD Deployment to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v7

      - name: 2. Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, mysql

      - name: 3. Install Composer Dependencies (Penting untuk Wayfinder)
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: 4. Setup Node.js Environment
        uses: actions/setup-node@v7
        with:
          node-version: '20'

      - name: 5. Install NPM & Build Inertia Assets
        run: |
          npm ci
          npm run build

      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
  # --------------------------

      - name: 6. Sync Built Assets (public/build) to VPS
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          ARGS: "-rltgoDzv --delete"
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USERNAME }}
          TARGET: "/var/www/my-app/public/build"
          SOURCE: "public/build/"

      - name: 7. Execute Deployment Script on VPS
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            /var/www/my-app/deploy.sh
